create extension if not exists pgcrypto;
create table if not exists users (user_id uuid primary key default gen_random_uuid(), created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists user_profiles (user_id uuid primary key references users(user_id) on delete cascade, sweet real not null default .5, salty real not null default .5, sour real not null default .5, umami real not null default .5, spicy real not null default .5, nutty real not null default .5, vector_version int not null default 0, baseline_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists foods (food_id text primary key, name text not null, category text not null, food_image_url text, sweet real not null, salty real not null, sour real not null, umami real not null, spicy real not null, nutty real not null, vector_version int default 1, source text default 'seed', rationale text, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists restaurants (restaurant_id text primary key, name text not null, category text not null, restaurant_type text, restaurant_image_url text, rating real, review_count int default 0, delivery_minutes text, delivery_fee int default 0, minimum_order int default 0, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists restaurant_menus (restaurant_menu_id text primary key, restaurant_id text references restaurants(restaurant_id) on delete cascade, food_id text references foods(food_id), menu_name text not null, menu_description text, menu_image_url text, price int not null, sweet real not null, salty real not null, sour real not null, umami real not null, spicy real not null, nutty real not null, menu_section text, is_representative boolean default false, is_popular boolean default false, is_available boolean default true, vector_version int default 1, evidence_count int default 0, source text default 'food_prior', created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists onboarding_responses (id bigint generated always as identity primary key, user_id uuid references users(user_id), question_index int not null, left_food_id text references foods(food_id), right_food_id text references foods(food_id), selected_food_id text references foods(food_id), created_at timestamptz default now());
create table if not exists orders (order_id uuid primary key default gen_random_uuid(), user_id uuid references users(user_id), restaurant_menu_id text references restaurant_menus(restaurant_menu_id), place_type text, time_segment text, weather_type text, context_snapshot jsonb, user_vector_before jsonb, user_vector_after jsonb, vector_version_before int, vector_version_after int, repeat_order boolean default false, taste_update_applied boolean default false, status text default 'completed', created_at timestamptz default now(), completed_at timestamptz);
create table if not exists reviews (review_id uuid primary key default gen_random_uuid(), order_id uuid references orders(order_id), user_id uuid references users(user_id), restaurant_id text references restaurants(restaurant_id), restaurant_menu_id text references restaurant_menus(restaurant_menu_id), rating int check(rating between 1 and 5), review_text text, status text default 'pending', user_vector_before jsonb, user_vector_after jsonb, user_update_applied boolean default false, restaurant_update_applied boolean default false, created_at timestamptz default now(), updated_at timestamptz default now());
create table if not exists review_evidence (evidence_id uuid primary key default gen_random_uuid(), review_id uuid references reviews(review_id) on delete cascade, claim_type text not null, axis text not null, level int, direction text, comparative boolean, confidence real, evidence_text text, model text, prompt_version text, created_at timestamptz default now());
create table if not exists recommendations (recommendation_id uuid primary key default gen_random_uuid(), user_id uuid references users(user_id), scope text, category text, candidate_ids jsonb, scores jsonb, context_snapshot jsonb, user_vector_snapshot jsonb, vector_version int, selected_food_id text, selected_restaurant_id text, selected_restaurant_menu_id text, created_at timestamptz default now());

-- Idempotency / lookup indexes for the PRD flows.
create unique index if not exists onboarding_user_question_uq on onboarding_responses(user_id, question_index);
create index if not exists restaurant_menus_food_idx on restaurant_menus(food_id);
create index if not exists restaurant_menus_restaurant_idx on restaurant_menus(restaurant_id);
create index if not exists orders_user_created_idx on orders(user_id, created_at desc);
create unique index if not exists reviews_order_uq on reviews(order_id);
create index if not exists review_evidence_review_idx on review_evidence(review_id);
create index if not exists recommendations_user_created_idx on recommendations(user_id, created_at desc);
