'use client';
import {useEffect,useState} from 'react';
import {Sparkles,ChevronLeft,ChevronRight,Star,Home,History,User,CloudRain,Clock,MapPin} from 'lucide-react';
import {api,post} from '../lib/api';
import SafeImage from './SafeImage';

type Vector={sweet:number;salty:number;sour:number;umami:number;spicy:number;nutty:number};
type Food={food_id:string;name:string;category:string;image_url:string;match:number;tags:string[]};
type PairFood={food_id:string;name:string;category:string;image_url:string};
type Rest={restaurant_id:string;restaurant_name:string;restaurant_image_url:string;restaurant_menu_id:string;menu_name:string;taste_match:number;rating:number;review_count:number;delivery_minutes:string;delivery_fee:number};
type Menu={restaurant_menu_id:string;food_id:string;name:string;description:string;image_url:string;price:number;section:string;representative:boolean;popular:boolean;taste_match:number};
const cats=[
 {label:'한식',value:'한식'},{label:'중식',value:'중식'},{label:'일식',value:'일식'},{label:'치킨',value:'치킨'},
 {label:'피자',value:'피자'},{label:'분식',value:'분식'},{label:'카페·디저트',value:'카페·디저트'},{label:'기타',value:'기타·글로벌'}
];
const labels:any={sweet:'단맛',salty:'짠맛',sour:'신맛',umami:'감칠맛',spicy:'매운맛',nutty:'고소함'};
const pct=(n:number)=>Math.round(n*100);
const localTimeSegment=()=>{const h=new Date().getHours();if(h>=5&&h<=10)return 'morning';if(h>=11&&h<=13)return 'lunch';if(h>=14&&h<=16)return 'afternoon';if(h>=17&&h<=21)return 'dinner';return 'late_night'};

export default function TasteLensApp(){
 const [uid,setUid]=useState(''); const [screen,setScreen]=useState('loading'); const [error,setError]=useState('');
 const [pair,setPair]=useState<any>(null); const [foods,setFoods]=useState<Food[]>([]); const [selectedFood,setSelectedFood]=useState<Food|null>(null);
 const [rests,setRests]=useState<Rest[]>([]); const [restaurant,setRestaurant]=useState<any>(null); const [menus,setMenus]=useState<Menu[]>([]); const [selectedMenu,setSelectedMenu]=useState<Menu|null>(null);
 const [profile,setProfile]=useState<Vector|null>(null); const [orders,setOrders]=useState<any[]>([]); const [lastOrder,setLastOrder]=useState<any>(null);
 const [place,setPlace]=useState('home'); const [weather,setWeather]=useState('normal'); const [temperature,setTemperature]=useState<number|null>(null); const [recommendationId,setRecommendationId]=useState(''); const [review,setReview]=useState(''); const [rating,setRating]=useState(5); const [reviewResult,setReviewResult]=useState<any>(null);
 const request=async(fn:()=>Promise<any>)=>{try{setError('');return await fn()}catch(e:any){setError(e.message||'오류가 발생했습니다');throw e}};
 useEffect(()=>{(async()=>{try{const h:any=await api('/health'); if(!h.supabase_configured){setError('Supabase 환경변수가 설정되지 않았습니다. API의 .env를 먼저 설정하세요.');setScreen('setup');return}
   let id=localStorage.getItem('taste-lens-user-id'); if(!id){const u:any=await post('/v1/users',{});id=u.user_id;localStorage.setItem('taste-lens-user-id',id!)} setUid(id!);
   const n:any=await api(`/v1/onboarding/${id}/next`); if(n.completed){await loadProfile(id!);setScreen('home')} else {setPair(n);setScreen('onboarding')}
 }catch(e:any){setError(e.message);setScreen('setup')}})()},[]);
 const loadProfile=async(id=uid)=>{const p:any=await api(`/v1/users/${id}/profile`);setProfile(p.vector)};
 const nextPair=async()=>{const n:any=await api(`/v1/onboarding/${uid}/next`);if(n.completed){await loadProfile();setScreen('home')}else setPair(n)};
 const choose=async(fid:string)=>{await request(()=>post(`/v1/onboarding/${uid}/choice`,{left_food_id:pair.left.food_id,right_food_id:pair.right.food_id,selected_food_id:fid}));await nextPair()};
 const recommend=async(category?:string)=>{const body={user_id:uid,scope:category?'category':'auto',category:category||null,place_type:place,time_segment:localTimeSegment(),weather_type:weather,temperature};const r:any=await request(()=>post('/v1/recommendations',body));setRecommendationId(r.recommendation_id);setFoods(r.foods);setScreen('foods')};
 const openFood=async(f:Food)=>{setSelectedFood(f);if(recommendationId)await post(`/v1/recommendations/${recommendationId}/selection`,{selected_food_id:f.food_id});const r:any=await request(()=>api(`/v1/foods/${f.food_id}/restaurants?user_id=${uid}&place_type=${place}&weather_type=${weather}&time_segment=${localTimeSegment()}`));setRests(r.restaurants);setScreen('restaurants')};
 const openRestaurant=async(r:Rest)=>{if(recommendationId)await post(`/v1/recommendations/${recommendationId}/selection`,{selected_restaurant_id:r.restaurant_id});const d:any=await request(()=>api(`/v1/restaurants/${r.restaurant_id}?user_id=${uid}&place_type=${place}&weather_type=${weather}&time_segment=${localTimeSegment()}`));setRestaurant(d.restaurant);setMenus(d.menus);setScreen('restaurant')};
 const order=async()=>{if(!selectedMenu)return;if(recommendationId)await post(`/v1/recommendations/${recommendationId}/selection`,{selected_restaurant_menu_id:selectedMenu.restaurant_menu_id});const o:any=await request(()=>post('/v1/orders',{user_id:uid,restaurant_menu_id:selectedMenu.restaurant_menu_id,place_type:place,time_segment:localTimeSegment(),weather_type:weather,temperature}));setLastOrder(o);await loadProfile();setScreen('done')};
 const loadOrders=async()=>{const o:any=await request(()=>api(`/v1/users/${uid}/orders`));setOrders(o.orders);setScreen('orders')};
 const submitReview=async()=>{if(!lastOrder)return;const r:any=await request(()=>post('/v1/reviews',{user_id:uid,order_id:lastOrder.order_id,rating,review_text:review}));setReviewResult(r);await loadProfile();setScreen('reviewDone')};
 const detectWeather=()=>{if(!navigator.geolocation){setError('브라우저 위치 권한을 사용할 수 없습니다.');return}navigator.geolocation.getCurrentPosition(async pos=>{try{const w:any=await api(`/v1/weather?latitude=${pos.coords.latitude}&longitude=${pos.coords.longitude}`);setWeather(w.weather_type);setTemperature(w.temperature);setError('')}catch(e:any){setError(e.message)}},()=>setError('날씨 자동 반영을 위해 위치 권한이 필요합니다.'))};
 const nav=<nav className="bottom"><button onClick={()=>setScreen('home')} className={screen==='home'?'active':''}><Home/>홈</button><button onClick={loadOrders}><History/>주문내역</button><button onClick={async()=>{await loadProfile();setScreen('profile')}}><User/>내 취향</button></nav>;
 if(screen==='loading')return <main className="app pad"><h2>Taste Lens 불러오는 중…</h2></main>;
 if(screen==='setup')return <main className="app pad"><h1>연결 설정이 필요합니다</h1><p>{error}</p><p><b>필수:</b> SUPABASE_URL, SUPABASE_SECRET_KEY</p><p><b>리뷰 분석:</b> UPSTAGE_API_KEY</p></main>;
 if(screen==='onboarding')return <main className="app onboarding"><div className="on-head"><span className="eyebrow"><Sparkles/> Taste Lens 시작하기</span><h1>몇 번의 선택으로<br/>내 입맛을 찾아볼게요.</h1><p>카테고리가 아니라 맛의 차이를 학습합니다.</p><div className="progress"><i style={{width:`${(pair.question_index-1)*10}%`}}/></div><span className="qcount">Q{pair.question_index} / 10</span></div><h2>지금 둘 중 하나를 먹는다면?</h2><div className="pair"><Choice f={pair.left} onClick={()=>choose(pair.left.food_id)}/><span className="vs">VS</span><Choice f={pair.right} onClick={()=>choose(pair.right.food_id)}/></div>{error&&<p>{error}</p>}</main>;
 let body:any=null;
 if(screen==='home')body=<><Top title="배달"/><section className="pad hero"><div><span className="tiny">PERSONAL FOOD DISCOVERY</span><h1>오늘 뭐 먹지?<br/><em>내 입맛</em>으로 찾아보세요.</h1></div><Sparkles/></section><section className="pad"><div className="catgrid">{cats.map(c=><button key={c.value} onClick={()=>recommend(c.value)}><span>🍽️</span>{c.label}</button>)}</div><button className="lensBanner" onClick={()=>setScreen('lens')}><span className="lensIcon"><Sparkles/></span><div><b>취향렌즈</b><small>지금 내 입맛에 맞는 음식 찾기</small></div><ChevronRight/></button><div className="contextCard"><b>현재 추천 Context</b><div><span><MapPin/> {place}</span><span><Clock/>현재 시간대</span><span><CloudRain/> {weather}</span></div></div></section>{nav}</>;
 if(screen==='lens')body=<><Top title="취향렌즈" back={()=>setScreen('home')}/><section className="pad"><div className="lensTitle"><Sparkles/><div><h1>오늘은 어떻게 찾아볼까요?</h1><p>장소·시간·날씨를 현재 취향에 함께 반영합니다.</p></div></div><button className="auto" onClick={()=>recommend()}><span>✨</span><div><b>알아서 추천</b><small>70개 음식 중 지금 가장 잘 맞는 Top 5</small></div><ChevronRight/></button><h3>카테고리로 찾기</h3><div className="lensCats">{cats.map(c=><button key={c.value} onClick={()=>recommend(c.value)}>{c.label}<ChevronRight/></button>)}</div></section>{nav}</>;
 if(screen==='foods')body=<><Top title="음식 추천" back={()=>setScreen('lens')}/><section className="pad"><div className="sectionlead"><div><span className="tiny">TASTE MATCH</span><h1>지금 내 입맛에 가까운 음식</h1></div></div><div className="foodlist">{foods.map((f,i)=><button className="foodcard" key={f.food_id} onClick={()=>openFood(f)}><SafeImage src={f.image_url} alt={f.name} kind="food"/><div className="foodcopy"><span className="rank">#{i+1} · {f.category}</span><h3>{f.name}</h3><b className="match"><Sparkles/> 취향 일치 {pct(f.match)}%</b><div className="tags">{f.tags.map(t=><span key={t}>{t}</span>)}</div></div><ChevronRight/></button>)}</div></section>{nav}</>;
 if(screen==='restaurants')body=<><Top title={`${selectedFood?.name} 식당`} back={()=>setScreen('foods')}/><section className="pad"><div className="selectedFood"><SafeImage src={selectedFood?.image_url} alt={selectedFood?.name||'선택한 음식'} kind="food"/><div><span className="tiny">선택한 음식</span><h2>{selectedFood?.name}</h2><b className="match"><Sparkles/> 취향 일치 {selectedFood?pct(selectedFood.match):0}%</b></div></div><div className="restlist">{rests.map(r=><button className="restcard" key={r.restaurant_menu_id} onClick={()=>openRestaurant(r)}><SafeImage src={r.restaurant_image_url} alt={r.restaurant_name} kind="restaurant"/><div><h3>{r.restaurant_name}</h3><b className="match"><Sparkles/> {r.menu_name} 내 취향 {pct(r.taste_match)}%</b><p><Star/> {r.rating} <span>리뷰 {r.review_count}</span></p><small>{r.delivery_minutes} · {r.delivery_fee===0?'무료배달':`배달비 ${r.delivery_fee.toLocaleString()}원`}</small></div><ChevronRight/></button>)}</div></section>{nav}</>;
 if(screen==='restaurant')body=<><Top title={restaurant?.name} back={()=>setScreen('restaurants')}/><div className="restHero"><SafeImage src={restaurant?.restaurant_image_url} alt={restaurant?.name||'식당'} kind="restaurant" style={{width:'100%',height:'100%'}} priority/><div className="shade"/></div><section className="pad restaurantInfo"><h1>{restaurant?.name}</h1><p><Star/> {restaurant?.rating} · 리뷰 {restaurant?.review_count}</p><div className="deliveryInfo"><span>{restaurant?.delivery_minutes}</span><span>{restaurant?.delivery_fee===0?'무료배달':`배달비 ${restaurant?.delivery_fee?.toLocaleString()}원`}</span><span>최소 {restaurant?.minimum_order?.toLocaleString()}원</span></div><div className="notice"><Sparkles/>기존 메뉴 순서는 유지하고 개인 Taste Match만 추가합니다.</div><div className="menulist">{menus.map(m=><button key={m.restaurant_menu_id} onClick={async()=>{setSelectedMenu(m);if(recommendationId)await post(`/v1/recommendations/${recommendationId}/selection`,{selected_restaurant_menu_id:m.restaurant_menu_id});setScreen('cart')}}><div>{m.representative&&<span className="badge">대표 메뉴</span>}<h3>{m.name}</h3><b className="match"><Sparkles/> 내 취향 {pct(m.taste_match)}%</b><p>{m.description}</p><strong>{m.price.toLocaleString()}원</strong></div><SafeImage src={m.image_url} alt={m.name} kind="menu"/></button>)}</div></section>{nav}</>;
 if(screen==='cart'&&selectedMenu)body=<><Top title="메뉴 선택" back={()=>setScreen('restaurant')}/><section className="pad cart"><SafeImage className="cartimg" src={selectedMenu.image_url} alt={selectedMenu.name} kind="menu"/><h1>{selectedMenu.name}</h1><span className="bigmatch"><Sparkles/> 내 취향 {pct(selectedMenu.taste_match)}%</span><p>{selectedMenu.description}</p><div className="price">{selectedMenu.price.toLocaleString()}원</div><button className="primary" onClick={order}>주문하기</button></section>{nav}</>;
 if(screen==='done')body=<><Top title="주문 완료"/><section className="pad done"><div className="doneicon">✓</div><h1>주문이 완료됐어요.</h1><p>이번 주문은 자동으로 내 Taste Vector에 반영되었습니다.</p><details><summary>내 취향 변화 보기</summary><pre>{JSON.stringify({before:lastOrder?.user_vector_before,after:lastOrder?.user_vector_after},null,2)}</pre></details><button className="secondary" onClick={()=>setScreen('home')}>홈으로 가기</button><button className="primary" onClick={loadOrders}>주문 내역 보기</button></section>{nav}</>;
 if(screen==='orders')body=<><Top title="주문 내역" back={()=>setScreen('home')}/><section className="pad"><div className="orderlist">{orders.map(o=><div className="ordercard" key={o.order_id}><SafeImage src={o.menu_image_url} alt={o.menu_name||'주문 메뉴'} kind="menu"/><div><small>{o.restaurant_name}</small><h3>{o.menu_name}</h3><p>{new Date(o.created_at).toLocaleString()}</p></div>{o.reviewed?<span className="reviewed">리뷰 완료</span>:<button onClick={()=>{setLastOrder(o);setReview('');setRating(5);setScreen('review')}}>리뷰 작성</button>}</div>)}</div></section>{nav}</>;
 if(screen==='review')body=<><Top title="리뷰 작성" back={()=>setScreen('orders')}/><section className="pad review"><h2>음식은 어떠셨나요?</h2><div className="stars">{[1,2,3,4,5].map(n=><button key={n} className={n<=rating?'on':''} onClick={()=>setRating(n)}>★</button>)}</div><label>리뷰</label><textarea value={review} onChange={e=>setReview(e.target.value)} placeholder="예: 다른 집보다 덜 달고 꽤 매웠어요. 저는 조금 더 매워도 좋을 것 같아요."/><small className="hint">평점은 만족도 신호이며 Taste Vector를 직접 바꾸지 않습니다. Taste는 리뷰 문장에서 Solar Pro 4가 분리 추출합니다.</small><button className="primary" disabled={!review.trim()} onClick={submitReview}>리뷰 등록</button></section>{nav}</>;
 if(screen==='reviewDone')body=<><Top title="리뷰 등록 완료"/><section className="pad done"><div className="doneicon">✓</div><h1>리뷰가 등록됐어요.</h1><p>{reviewResult?.user_update_applied?'명시적인 개인 선호 표현이 낮은 가중치로 취향에 반영됐습니다.':'개인 선호에 대한 명확한 표현이 없어 User Taste는 바뀌지 않았습니다.'}</p><details><summary>리뷰 취향 변화 보기</summary><pre>{JSON.stringify(reviewResult?.analysis,null,2)}</pre></details><button className="primary" onClick={loadOrders}>주문 내역으로 돌아가기</button></section>{nav}</>;
 if(screen==='profile')body=<><Top title="내 취향" back={()=>setScreen('home')}/><section className="pad profile"><div className="profileHero"><Sparkles/><div><span>Taste Vector</span><h1>현재 나의 입맛</h1><p>Pairwise·주문·명시적 리뷰 표현에서 점진적으로 학습됩니다.</p></div></div>{profile&&<div className="radarFake">{Object.entries(profile).map(([k,v])=><div key={k}><span>{labels[k]}</span><i><b style={{width:`${Number(v)*100}%`}}/></i><strong>{pct(Number(v))}</strong></div>)}</div>}<div className="settings"><h3>현재 Context</h3><label>장소<select value={place} onChange={e=>setPlace(e.target.value)}><option value="home">집</option><option value="school">학교</option><option value="work">회사</option><option value="other">기타</option></select></label><label>날씨<select value={weather} onChange={e=>setWeather(e.target.value)}><option value="normal">보통</option><option value="rain">비</option><option value="hot">더움</option><option value="cold">추움</option></select></label><button className="secondary" onClick={detectWeather}>현재 위치로 날씨 자동 반영</button>{temperature!==null&&<small>Open-Meteo 현재 기온: {temperature.toFixed(1)}℃</small>}</div></section>{nav}</>;
 return <main className="app">{body}{error&&<div style={{position:'fixed',bottom:90,left:'50%',transform:'translateX(-50%)',width:'min(440px,90vw)',padding:12,background:'#fff1ef',border:'1px solid #ffd4ca',borderRadius:12,zIndex:50}}>{error}</div>}</main>;
}
function Choice({f,onClick}:{f:PairFood,onClick:()=>void}){return <button className="choice" onClick={onClick}><SafeImage src={f.image_url} alt={f.name} kind="food"/><div><span>{f.category}</span><h3>{f.name}</h3><small>이 음식을 선택</small></div></button>}
function Top({title,back}:{title:string,back?:()=>void}){return <header className="topbar">{back?<button className="icon" onClick={back}><ChevronLeft/></button>:<span className="brandmark">TL</span>}<b>{title}</b><span className="top-spacer"/></header>}
